version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:root@mysql:3306/granada_sport   
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: granada_sport             
      MYSQL_PASSWORD: root                   
      MYSQL_ROOT_PASSWORD: root              
    ports:
      - "3306:3306"          
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
    